server:
  port: 8085

hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
    desc: 黑马商城交易服务接口文档
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123