server:
  port: 8081

hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城商品服务服务接口文档"
    package: com.hmall.item.controller
    desc: 黑马商城商品服务接口文档

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123